# This file is the entry point to configure your own services.
# Files in the packages/ subdirectory configure your dependencies.

# Put parameters here that don't need to change on each machine where the app is deployed
# https://symfony.com/doc/current/best_practices.html#use-parameters-for-application-configuration
parameters:

services:
    # default configuration for services in *this* file
    _defaults:
        autowire: true      # Automatically injects dependencies in your services.
        autoconfigure: true # Automatically registers your services as commands, event subscribers, etc.

    # makes classes in src/ available to be used as services
    # this creates a service per class whose id is the fully-qualified class name
    App\:
        resource: '../src/'
        exclude:
            - '../src/DependencyInjection/'
            - '../src/Domain/Entity/'
            - '../src/Kernel.php'

    App\Application\Service\UserService:
        arguments:
            $userRepository: '@App\Infrastructure\Repository\UserRepository'

    App\Application\GetUser\GetUserHandler:
        arguments:
            - '@App\Domain\Repository\UserRepositoryInterface'

    App\Application\BuilderUserProfile\CreateUserProfileHandler:
        arguments:
            - '@App\Domain\Repository\UserRepositoryInterface'
            - '@App\Domain\Repository\UserProfileRepositoryInterface'

    App\Infrastructure\Repository\UserRepositoryInterface:
        alias: App\Infrastructure\Persistence\DoctrineUserRepository

    App\Infrastructure\Repository\UserProfileRepositoryInterface:
        alias: App\Infrastructure\Persistence\DoctrineUserProfileRepository

    App\Presentation\UserController:
        autowire: true
        autoconfigure: true
        public: true

    # ABSTRACT FACTORY
    App\Application\Factory\Form\HtmlFormFactory: ~
    App\Application\Factory\Form\SlackFormFactory: ~
    App\Application\Factory\Form\ConsoleFormFactory: ~

    App\Application\Factory\Form\FormFactoryResolver:
        arguments:
            $htmlFactory: '@App\Application\Factory\Form\HtmlFormFactory'
            $slackFactory: '@App\Application\Factory\Form\SlackFormFactory'
            $consoleFactory: '@App\Application\Factory\Form\ConsoleFormFactory'
    # /ABSTRACT FACTORY

    App\Application\BuilderUserProfile\BuildFormHandler:
        arguments:
            - '@App\Application\Factory\Form\FormFactoryResolver'